### ISSUE TITLE
issue with George not psychologically

### ISSUE THREAD

**Issue by issuestest** [cephalin/testissues#14]
[AB#9](https://dev.azure.com/syncedorg/b545e17f-bbf4-4a68-bea2-e006a6a76a96/_workitems/edit/9)

**Comment by cephalin** [comment]
[AB#9](https://dev.azure.com/syncedorg/b545e17f-bbf4-4a68-bea2-e006a6a76a96/_workitems/edit/9) closed.

**Comment by cephalin** [comment]
[AB#9](https://dev.azure.com/syncedorg/b545e17f-bbf4-4a68-bea2-e006a6a76a96/_workitems/edit/9) assigned to Cephas Lin.

**Comment by cephalin** [comment]
[AB#9](https://dev.azure.com/syncedorg/b545e17f-bbf4-4a68-bea2-e006a6a76a96/_workitems/edit/9) assigned to Cephas Lin.
