### ISSUE TITLE
restart automation

### ISSUE THREAD

**Issue by issuestest** [cephalin/testissues#15]
[AB#10](https://dev.azure.com/syncedorg/b545e17f-bbf4-4a68-bea2-e006a6a76a96/_workitems/edit/10)

**Comment by cephalin** [comment]
[AB#10](https://dev.azure.com/syncedorg/b545e17f-bbf4-4a68-bea2-e006a6a76a96/_workitems/edit/10) assigned to Cephas Lin.

**Comment by cephalin** [comment]
[AB#10](https://dev.azure.com/syncedorg/b545e17f-bbf4-4a68-bea2-e006a6a76a96/_workitems/edit/10) unassigned.

**Comment by cephalin** [comment]
[AB#10](https://dev.azure.com/syncedorg/b545e17f-bbf4-4a68-bea2-e006a6a76a96/_workitems/edit/10) assigned to Cephas Lin.

**Comment by cephalin** [comment]
[AB#10](https://dev.azure.com/syncedorg/b545e17f-bbf4-4a68-bea2-e006a6a76a96/_workitems/edit/10) assigned to Cephas Lin.

**Comment by cephalin** [comment]
[AB#10](https://dev.azure.com/syncedorg/b545e17f-bbf4-4a68-bea2-e006a6a76a96/_workitems/edit/10) unassigned.

**Comment by cephalin** [comment]
[AB#10](https://dev.azure.com/syncedorg/b545e17f-bbf4-4a68-bea2-e006a6a76a96/_workitems/edit/10) assigned to Cephas Lin.

**Comment by cephalin** [comment]
[AB#10](https://dev.azure.com/syncedorg/b545e17f-bbf4-4a68-bea2-e006a6a76a96/_workitems/edit/10) closed.

**Comment by cephalin** [comment]
[AB#10](https://dev.azure.com/syncedorg/b545e17f-bbf4-4a68-bea2-e006a6a76a96/_workitems/edit/10) closed.

**Comment by cephalin** [comment]
[AB#10](https://dev.azure.com/syncedorg/b545e17f-bbf4-4a68-bea2-e006a6a76a96/_workitems/edit/10) closed.
